type_name:
  allowed_symbols: "_"
identifier_name:
  min_length: 2
line_length:
  warning: 220
  error: 250
disabled_rules:
  - trailing_whitespace
  - type_name
  - multiple_closures_with_trailing_closure
  - no_space_in_method_call