name: VtDashboard
options:
  bundleIdPrefix: com.chuysan.vtuber
  deploymentTarget:
    macOS: 11.0
packages:
  Kingfisher:
    url: https://github.com/onevcat/Kingfisher
    exactVersion: 6.1.1
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    exactVersion: 5.4.1
  Firebase:
    url: https://github.com/firebase/firebase-ios-sdk.git
    exactVersion: 7.10.0
targets:
  VtDashboard:
    type: application
    platform: macOS
    sources: 
      - path: VtDashboard
        excludes: &testTarget
          - "**/*Tests.swift"
    dependencies:
      - package: Kingfisher
      - package: Alamofire
      - package: Firebase
        product: FirebaseAuth
    postBuildScripts:
      - name: Copy Google Service Info plist
        path: "scripts/copy_appropriate_google-service-info-plist.sh"
  VtDashboardTests:
    type: bundle.unit-test
    platform: macOS
    sources:
      - path: VtDashboard
        includes: *testTarget
    dependencies:
      - target: VtDashboard
schemes:
  VtDashboard:
    build:
      config: Debug
      targets:
        VtDashboard: all
    run:
      config: Debug
    test:
      targets:
        - name: VtDashboardTests
      gatherCoverageData: true
      coverageTargets:
        - VtDashboard
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
