name: vtdashboard
options:
  bundleIdPrefix: com.chuysan.vtuber.vtdashboard
  deploymentTarget:
    macOS: 11.0
packages:
  KingFisher:
    url: https://github.com/onevcat/Kingfisher
    from: 6.1.1
  Alamofire:
    url: https://github.com/Alamofire/Alamofire
    from: 5.4.1
targets:
  vtdashboard:
    type: application
    platform: macOS
    sources: 
      - path: vtdashboard
    dependencies:
      - package: KingFisher
      - package: Alamofire
