# This workflows refer from this article https://qiita.com/koogawa/items/ddf86b56d6b82ae11473

name: iOS build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - name: Show Xcode version
        run: xcodebuild -version
      - name: Install Mint
        run: brew install mint
      - name: Install Bundler
        run: gem install bundler
      - name: make setup
        run: make setup
      - name: Test
        run: xcodebuild -scheme VtDashboard test -destination 'platform=iOS Simulator,name=iPhone 12 Pro' \
      ## Disable archiving due to not having provisioning profile
      # - name: Archive
      #   run: xcodebuild -scheme VtDashboard archive -archivePath archive
      # - name: 'Upload Artifact'
      #   uses: actions/upload-artifact@v2
      #   with:
      #     name: Archive
      #     path: archive.xcarchive
      #     retention-days: 7
